apiVersion: "cluster.kurl.sh/v1beta1"
kind: "Installer"
metadata: 
  name: "latest"
spec: 
  kubernetes: 
    version: "1.26.x"
  weave: 
    version: "2.6.x"
  contour: 
    version: "1.23.x"
  prometheus: 
    version: "0.60.x"
  registry: 
    version: "2.8.x"
  containerd: 
    version: "1.6.x"
  ekco: 
    version: "latest"
  minio: 
    version: "2022-12-12T19-27-27Z"

  # OpenEBS is the default PV provisioner, and
  # will work for single node clusters, or for
  # applications that handle data replication
  # between nodes themselves (MongoDB, Cassandra,
  # etc). If your requirements are different than
  # this, see
  # https://kurl.sh/docs/create-installer/choosing-a-pv-provisioner
  #
  openebs: 
    version: "3.3.x"
    isLocalPVEnabled: true
    localPVStorageClassName: "default"

